# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-12 06:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamechannels', '0002_auto_20171211_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordset',
            name='letters',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
